[[distributed-revision-control]]

=== 分散型バージョン管理システム「Git」について

このように「ファイル名を変更するだけのバージョン管理」では、多人数でファイルを編集したいときに困る事になります。

また、内容を前のものに戻しづらい・戻せないということが起こりやすいため、紅莉栖と岡部で作業したところが被ってしまい片方の変更点が消えた結果、どちらかが作業をやり直し……ということが起きます。

そこで、この書籍のテーマである「Git」が登場します。「Git」は「分散型バージョン管理システム」といわれるものです。

==== Gitの概要

上記でも書きましたが「Git」は「分散型バージョン管理システム」の一つです。他の分散型バージョン管理システムとして「Mercurial」「Bazaar」などがありますが、この書籍では特に触れません。

Git の読み方は「ギット」です。footnote:[+http://dictionary.reference.com/browse/git+]イギリス英語のスラングで「バカ」「卑劣な」という意味があるそうです。なぜこの名前が付いたかはWikipediafootnote:[http://ja.wikipedia.org/wiki/Git#.E5.90.8D.E5.89.8D.E3.81.AE.E7.94.B1.E6.9D.A5] や、Git FAQ (英語)footnote:[https://git.wiki.kernel.org/index.php/GitFaq#Why_the_.27Git.27_name.3F] を見てみてください。

Git は「リポジトリ」という「ファイルのスナップショットfootnote:[ソースコードなどを任意のタイミングで抜き出したもの。詳しくは http://e-words.jp/w/E382B9E3838AE38383E38397E382B7E383A7E38383E38388.html を参照してください。]が保管されている場所」があります。

スナップショットを保存する方法ですが、Git には「コミットfootnote:[第三章の「作業内容を記録する」で解説しています。]」という「スナップショットを任意のタイミングで保存する機能」があります。その機能を使う事により、自分がした作業を記録することができます。

この「コミット」ですが、Steins;Gate のゲームシステムで例えると「セーブ」と言えます。そして「セーブデータ」が「リポジトリ」です。

ただし Git の場合は、セーブデータの任意の場所に戻ることができます。それは「特定のエンディングに進もうとしてセーブしておいたデータに、誤って別のデータをセーブしてしまっても元に戻せる」ということを意味します。

また Git で他の人と作業内容を共有したいという場合は、ネットワーク上に共有リポジトリを用意しておき、そこへ自分の作業内容を送信します。

作業内容の送信をする機能を「プッシュfootnote:[第三章の「リモートリポジトリに作業内容を送る」で解説しています。]」と言います。

==== Gitの利点

Git の概要でも書きましたが、作業した内容を作業前の状態に戻したいといったときでも「チェックアウトfootnote:[第三章の「作業内容を無かったことにする」で解説しています。]」や「リバートfootnote:[Steins;Git では解説していないため各自で「git revert とは」と入力して検索してみてください]」という機能を使えば、手軽に戻すことができます。

これによりファイルを編集する際に、ファイル名に日付などを追加してからコピーということをしなくて済むので、編集すべきファイルがどれなのか分からなくなる問題が無くなります。

また、多人数での編集も「プルfootnote:[第三章の「リモートリポジトリの変更内容を自分のPC上のリポジトリに取り込む」で解説しています。]」という「自分の PC 上のリポジトリに、ネットワーク上にあるリポジトリの最新の内容を反映する機能」を使うことにより、他の人が変更した点も取り込めます。

なので、同じファイルを編集してしまったために、どちらかの編集内容が消えてしまうという事が少なくなります。これで岡部と紅莉栖も喧嘩しなくなるでしょう。
