[[chapter0-introduction]]
= はじめに
:imagesdir: Ch0_Introduction/

本書は「Gitの使い方を、Steins;Gateの世界観を通して説明する」ことを目的にして執筆しました。

本書の目標としては、「Steins;Gateのアニメを全話見た人や、ゲームで全てのエンディングを見た人で、Gitに触れたことがない、もしくは触り始めたばかりという人が、Gitの使い方を知るきっかけになる」ということです。

そのため、Gitの全ての機能の説明をしません。自分が普段使うことが多い機能を中心に書いています。

## 謝辞

https://twitter.com/kyo_ago/[@kyo_ago] の下記のツイートにより、本書を書こうと思いました。

> 今日の飲み会を一言でいうと「シュタゲで分かるgithub」
> https://twitter.com/kyo_ago/status/193703522351595522[2012年4月21日]

> 結局「シュタゲで覚えるgit」って誰も書かなかったんですか？
> https://twitter.com/kyo_ago/status/413586733008044032[2013年12月19日]

また https://twitter.com/search?f=realtime&q=%23SteinsGit[#SteinsGit] というTwitterのハッシュタグを通じていろいろと助言をいただいたり、 https://twitter.com/watilde[@watilde] と一緒にレビュー会というのを開いていただきました。

他にも https://gitter.im/o2project/steins-git[Gitter] というチャットサービス上で https://github.com/yosiwo[yosiwo] さんには構成について助言をもらいました。

そして http://blog.o2p.jp/2014/07/23/c86-steins-git.html[「シュタゲで分かるGit」をテーマにした「Steins;Git」という薄い本をC86(コミックマーケット86)で頒布します(予定)] という記事を公開した際に、期待する声や欲しいという声をあげてくださった皆さんには、執筆を頑張る気力をもらいました。

本当にありがとうございます。

// <<< PAGE BREAK PDFのみ
<<<

## 本書の構成

本書は全三章とあとがきから成り立っています。

1. 第一章では、バージョン管理とは何かということから説明し、その中でGitがどんな特徴を持っているかについて説明します。
2. 第二章では、バージョン管理システムの中でも、なぜGitを使うのかというのを利点を提示して説明します。
3. 第三章では、Gitで自分がよく使う機能について説明します。
4. あとがきでは、Gitをラボメンで使うなど、複数人で使う場合に、その助けとなるサービスを紹介します。また、本書を書くにあたって参照したサイトや書籍を紹介します。
