[[chapter0-introduction]]
= はじめに
:imagesdir: Ch0_Introduction/

本書は「Gitの使い方を、Steins;Gateの世界観を通して説明する」事を目的にして執筆しました。

本書の目標としては、「Steins;Gateのアニメを全話見た人や、ゲームで全てのエンディングを見た人で、Gitに触れた事がない、もしくは触り始めたばかりという人が、Gitの使い方を知るきっかけになる」という事です。

故に、Gitの全ての機能の説明をしません。普段、自分が使うことが多いコマンドを中心に書いています。

## 謝辞

https://twitter.com/kyo_ago/[@kyo_ago] の下記のツイートにより、本書を書こうと思いました。また https://twitter.com/search?f=realtime&q=%23SteinsGit[#SteinsGit] というTwitterのハッシュタグを通じて、いろいろと助言をいただきました。

> 今日の飲み会を一言でいうと「シュタゲで分かるgithub」
> https://twitter.com/kyo_ago/status/193703522351595522[2012年4月21日]

> 結局「シュタゲで覚えるgit」って誰も書かなかったんですか？
> https://twitter.com/kyo_ago/status/413586733008044032[2013年12月19日]

また、 https://gitter.im/o2project/steins-git[Gitter] というチャットサービス上で、yosiwoさんには構成について助言をもらいました。

本当にありがとうございます。

// <<< PAGE BREAK PDFのみ
<<<

## 本書の構成

本書は全三章とあとがきから成り立っています。

1. 第一章では、バージョン管理とは何かという事から説明し、その中でGitがどんな特徴を持っているかについて説明します。
2. 第二章では、バージョン管理システムの中でも、なぜGitを使うのかというのを利点を提示して説明します。
3. 第三章では、実際にGitを使っていきます。Gitで自分がよく使うコマンドについて説明します。
4. あとがきでは、Gitをラボメンで使うなど、複数人で使う場合に、その助けとなるサービスを紹介します。また、本書を書くにあたって参照したサイトや書籍を紹介します。
