version: 2
updates:
  - package-ecosystem: npm
    assignees:
      - 'kubosho'
    directory: '/'
    schedule:
      interval: weekly
      time: '10:00'
      timezone: Asia/Tokyo
    versioning-strategy: increase
    open-pull-requests-limit: 20
