[[distributed-revision-control]]

== 分散型バージョン管理(Git)

次に分散型バージョン管理システムについて説明します。分散型バージョン管理には何種類かありますが、ここではこの書籍のテーマである「Git」を例に取り、集中型バージョン管理システムであるSVNと比べて、分散型バージョン管理システムであるGitには、どのような違いがあってどんな利点があるかを解説していきます。

=== Gitの概要

Gitは分散型バージョン管理システムの一つです。Gitの場合は自分のPC上に「リポジトリ」があり、自分の手元でで作業内容を記録(コミット)していくことができます。他人と作業内容を共有する場合は、ネットワーク上に共有用のリポジトリを用意しておき、そこへ自分の作業内容を送信(プッシュ)します。

この分散型バージョン管理システムというものは、SVNと比較した際の利点として、三つあります。その利点について、以下に書いていきます。

=== 一人で作業する場合は共有リポジトリがいらない

SVNは、作業内容を記録するために、まずはリポジトリ用のサーバーを用意することから始めないといけません。

これはまゆしぃを助けるため、何度も世界線を変えないといけないくらい大変なことです。とはいえ、まゆしぃを助けるために世界線を変えることを避けられないのと一緒で、作業内容を記録できるようにするためにサーバーを用意するということは避けられません。

Gitは、とても簡単な手順(第四章で説明します)をおこなうことで、作業内容の記録(コミット)をおこなうことができます。言うならば、最初のβ世界線からα世界線に飛んだところから始めることができるということです。

=== リポジトリを手元に持てる

SVNは、手元にリポジトリがなく、ネットワーク上にだけリポジトリがあります。これは、ローカル上にリポジトリを持たない分、ハードディスクやSSDに記録できることが増えることになるというメリットがありますが、一方で、ネットワーク環境が無いと作業内容の記録(コミット)や今までおこなった作業内容の履歴を見ることができません。

Gitは、通信が必要なのは共有するためのリポジトリに作業内容を送るときや、逆に他の人の作業内容を受け取るときのみとなります。それ以外はネットワーク接続がいりません。これで、オカリンもいついかなる場所でも未来ガジェットのアイデアを記録することができます。

=== 手元のリポジトリでいろいろと試せる

SVNは、リポジトリが共有のリポジトリしかないため、コマンドを気軽に試せる環境とは言えないです。

Gitは、手元にリポジトリがあるため、知らないGitのコマンドでも作業内容の送信さえおこなわなければ、気軽に試すことができます。手元のリポジトリがどうにもならなくなってしまった状態になってしまっても、再度共有リポジトリを手元にコピーすれば、元通りになります。

例えばまゆしぃやルカ子が何か役に立ちたいと思って、オカリンや紅莉栖からGitの使いかたを教えてもらうとなったときに、実際にGitのコマンドを試せることになります。
