[[distributed-revision-control]]

== 分散型バージョン管理(Git)

ここでようやく分散型バージョン管理が出てきます。

分散型バージョン管理には何種類かありますが、ここではこの書籍のテーマである「Git」を、集中型バージョン管理システムであるSVNと比べて、分散型バージョン管理システムであるGitには、どのような違いがあってどんな利点があるかを解説していきます。

=== Gitの概要

Gitは分散型バージョン管理の一つです。Gitの場合は自分のPC上に「リポジトリ」があり、自分の手元でで作業内容を記録(コミット)していくことができます。他人と作業内容を共有する場合は、ネットワーク上に共有用のリポジトリを用意しておき、そこへ自分の作業内容を送信(プッシュ)します。

=== SVNと比較したときの利点

SVNと比較した際、Gitの利点としては三つあります。

一つ目は、分散型バージョン管理という性質上、他人と作業内容を共有するためのリポジトリがいらないことです。

SVNは、作業内容を記録するために、まずはリポジトリ用のサーバーを用意することから始めないといけません。

これはまゆしぃを助けるため、何度も世界線を変えないといけないくらい大変なことです。とはいえ、まゆしぃを助けるために世界線を変えることを避けられないのと一緒で、作業内容を記録できるようにするためにサーバーを用意するということは避けられません。

Gitは、とても簡単な手順(第四章で説明します)をおこなうことで、作業内容の記録(コミット)をおこなうことができます。言うならば、α世界線からβ世界線に飛ぶ直前から始めることができるということです。

二つ目は、リポジトリを手元に持てるということです。

SVNは、手元にリポジトリがなく、ネットワーク上にだけリポジトリがあります。これは、ローカル上にリポジトリを持たない分、ハードディスクやSSDに記録できることが増えることになるというメリットがありますが、一方で、ネットワーク環境が無いと作業内容の記録(コミット)や今までおこなった作業内容の履歴を見ることができません。

Gitは、通信が必要なのは共有するためのリポジトリに作業内容を送るときや、逆に他の人の作業内容を受け取るときのみとなります。それ以外はネットワーク接続がいりません。これで、オカリンもいついかなる場所でも未来ガジェットのアイデアを記録することができます。

三つ目は、手元のリポジトリでいろいろと試せるということです。

SVNは、リポジトリが共有のリポジトリしかないため、コマンドを気軽に試せる環境とは言えないです。

Gitは、手元にリポジトリがあるため、知らないGitのコマンドでも作業内容の送信さえおこなわなければ、気軽に試すことができます。手元のリポジトリがどうにもならなくなってしまった状態になってしまっても、再度共有リポジトリを手元にコピーすれば、元通りになります。

例えばまゆしぃやルカ子が何か役に立ちたいと思って、オカリンや紅莉栖からGitの使いかたを教えてもらうとなったときに、実際にGitのコマンドを試せることになります。
